apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: dennisbaer/todoapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
         #  environment:
          #MONGO_URI: mongodb://mongo:27017/todoapp
          #JWT_SECRET: 3t6w9z$B&E)H@McQ
          #PORT: 8080 # Docker Chooses Port Automatically
        env:
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: backend-secret
                key: jwt-secret

          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-user
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-password
          - name: MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: mongo-url
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  
  selector:
    app: backend
  ports:
  - port: 8080
    targetPort: 8080
